apiVersion: v1
kind: Pod
metadata:
  name: pyspark-pod
  labels:
    app: pyspark-pod
spec:
  containers:
  - name: pyspark
    image: jupyter/pyspark-notebook:python-3.7.12
    ports:
    - containerPort: 4040
      name: pyspark
    - containerPort: 9999
      name: workers
    - containerPort: 9191
      name: blockmanager
    volumeMounts:
    - name: pyspark
      mountPath: /home/jovyan/SparkRegression.py
    command: ["/bin/bash", "-c"]
    args: 
    - |
      pip install elasticsearch
      echo "Starting PySpark Job"
      spark-submit --conf spark.blockManager.port=9191 --conf spark.driver.port=9999 --num-executors 2 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 --master spark://sp-master:7077 /home/jovyan/SparkRegression.py
    
    readinessProbe:
      httpGet:
        path: /
        port: 4040
      initialDelaySeconds: 40
      periodSeconds: 30
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 10
    livenessProbe:
      httpGet:
        path: /
        port: 4040
      initialDelaySeconds: 50
      periodSeconds: 30
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 10
  volumes:
  - name: pyspark
    hostPath:
      path: /SharedFS/SparkRegression.py
      type: File