name: sp-master

image: bde2020/spark-master:3.3.0-hadoop3.3

ports:
- port: 8090
  protocol: TCP
- port: 7077
  protocol: TCP

environment:
- name: INIT_DAEMON_STEP
  value: "setup_spark"
- name: SPARK_MASTER_WEBUI_PORT
  value: "8090"
- name: SPARK_WORKLOAD
  value: "master"
- name: SPARK_DRIVER_MEMORY
  value: "2g"

  