apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  type: NodePort
  ports:
  - name: kafka-ui
    port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  selector:
    app: kafka-ui