apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-pod
  labels:
    app: zookeeper-pod
spec:
  containers:
  - name: zookeeper-container
  
    image: confluentinc/cp-zookeeper:latest

    ports:
    - containerPort: 2181

    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"

    livenessProbe:
      tcpSocket:
        port: 2181
      initialDelaySeconds: 20
      periodSeconds: 10
    
    readinessProbe:
      tcpSocket:
        port: 2181
      initialDelaySeconds: 20
      periodSeconds: 10