apiVersion: batch/v1
kind: Job
metadata:
  name: init-kafka-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-init-container
        image: confluentinc/cp-kafka:latest
        command: ["/bin/bash", "-c"]
        args: 
        - |
            # blocks until kafka is reachable
            kafka-topics --bootstrap-server kafkaservice:9093 --list   

            echo -e 'Creating kafka topics'
            kafka-topics --bootstrap-server kafkaservice:9093 --create --if-not-exists --topic LiveTimingData --replication-factor 1 --partitions 1

            echo -e 'Successfully created the following topics:'
            kafka-topics --bootstrap-server kafkaservice:9093 --list