apiVersion: v1
kind: Service
metadata:
  name: kafkaservice
  labels:
    app: kafkaservice
spec:
    ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: zookeeper
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: init-port
      port: 9093
      targetPort: 9093
    selector:
      app: kafka-deployment