apiVersion: v1
kind: Pod
metadata:
  
  name: kafka-ui-pod
  labels:
    app: kafka-ui
spec:
  containers:
  - name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
    - containerPort: 8080
    env:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "F1"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "broker:29093"
    - name: KAFKA_CLUSTERS_0_ZOOKEEPER
      value: "broker:2181"
