apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka-deployment
    template:
        metadata:
            labels:
                app: kafka-deployment
        spec:
            containers:
            - name: zookeeper-container
              image: confluentinc/cp-zookeeper:latest
              ports:
              - containerPort: 2181
              - containerPort: 29092
              env:
              - name: ZOOKEEPER_CLIENT_PORT
                value: "2181"
              - name: ZOOKEEPER_TICK_TIME
                value: "2000"
              livenessProbe:
                tcpSocket:
                  port: 2181
                initialDelaySeconds: 15
                periodSeconds: 10

            - name: kafka-container
              image: confluentinc/cp-kafka:latest
              ports:
              - containerPort: 9093
              env:
              - name: KAFKA_BROKER_ID
                value: "1"
              - name: KAFKA_ZOOKEEPER_CONNECT
                value: "localhost:2181"
              - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT"
              - name: KAFKA_ADVERTISED_LISTENERS
                value: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://localhost:29092,PLAINTEXT_EXTERNAL://kafkaservice:9093"
              - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                value: "1"
              livenessProbe:
                  tcpSocket:
                      port: 9092
                  initialDelaySeconds: 15
                  periodSeconds: 10
              readinessProbe:
                  tcpSocket:
                      port: 9092
                  initialDelaySeconds: 15
                  periodSeconds: 10
            