apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka-deployment
    template:
        metadata:
            labels:
                app: kafka-deployment
        spec:
            containers:
            - name: kafka-container
              image: confluentinc/cp-kafka:latest
              ports:
              - containerPort: 9093
                name: external1
              - containerPort: 29093
                name: external2
              - containerPort: 29094
                name: external3
              env:
              - name: KAFKA_BROKER_ID
                value: "1"
              - name: KAFKA_ZOOKEEPER_CONNECT
                value: "zookeeper:2181"
              - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,KAFKA_UI:PLAINTEXT,SPARK:PLAINTEXT"
              - name: KAFKA_ADVERTISED_LISTENERS
                value: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://localhost:29092,PLAINTEXT_EXTERNAL://broker:9093,KAFKA_UI://broker:29093,SPARK://broker:29094"
              - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                value: "1"
              livenessProbe:
                  tcpSocket:
                      port: 9092
                  initialDelaySeconds: 15
                  periodSeconds: 10
              readinessProbe:
                  tcpSocket:
                      port: 9092
                  initialDelaySeconds: 15
                  periodSeconds: 10
            