apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
    ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: zookeeper
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: init-port
      port: 9093
      targetPort: 9093
      protocol: TCP
    - name: internal
      port: 29093
      targetPort: 29093
      protocol: TCP
    - name: spark
      port: 29094
      targetPort: 29094
      protocol: TCP
    selector:
      app: kafka-deployment