apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch-deployment