apiVersion: v1
kind: Pod
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
    containers:
    - name: sp-master
      image: bde2020/spark-master:3.3.0-hadoop3.3
      ports:
      - name: spark-ui
        containerPort: 8090
      - name: spark-master
        containerPort: 7077
      env:
      - name: INIT_DAEMON_STEP
        value: "setup_spark"
      - name: SPARK_MASTER_WEBUI_PORT
        value: "8090"
      - name: SPARK_WORKLOAD
        value: "master"
      - name: SPARK_DRIVER_MEMORY
        value: "1g"
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8090
        initialDelaySeconds: 20
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8090
        initialDelaySeconds: 20
        periodSeconds: 5