name: logstash

image: logstash:8.7.1

ports:
- protocol: TCP
  port: 5000
- protocol: TCP
  port: 5001
- protocol: TCP
  port: 5002

environment:
- name: LS_JAVA_OPTS
  value: -Xms1g -Xmx2g

volumes:
- name: logstash-config-pipelines-confs
  hostPath:
    path: /pipeline/confs/
    type: Directory
- name: logstash-pipelinesyml
  hostPath:
    path: /pipeline/pipelines.yml
    type: File


volumeMounts:
- name: logstash-pipelinesyml
  mountPath: /usr/share/logstash/config/pipelines.yml
- name: logstash-config-pipelines-confs
  mountPath: /usr/share/logstash/pipeline/