apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  containers:
  - name: kibana
    image: kibana:8.7.1
    ports:
    - containerPort: 5601
    env:
    - name: ELASTICSEARCH_HOSTS
      value: http://elasticsearch:9200
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    livenessProbe:
      httpGet:
        path: /
        port: 5601
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 5601
      initialDelaySeconds: 30
      periodSeconds: 10