apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-deployment
    spec:
      {{ if .Values.ports}}
      hostname: {{ .Values.name }}
      {{ end }}
      containers:
      - name: {{ .Values.name }}-container
        image: {{ .Values.image }}
        {{ if .Values.ports }}
        ports:
        {{ range .Values.ports }}
        - name: {{ .port }}-{{ .protocol | lower }}
          containerPort: {{ .port }}
        {{ end }}
        {{ end }}

        {{- if .Values.environment }}
        env:
        {{ range .Values.environment }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}

        {{- if .Values.commands }}
        command: ["/bin/bash", "-c"]
        args:
        - |
            {{ range .Values.commands }}
            {{ .command }}
            {{ end }}
        {{- end }}

        {{- if .Values.volumeMounts }}
        volumeMounts:
        {{- range .Values.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- end }}

      {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}
        {{- if .configMap }}
        configMap:
          name: {{ .configMap.name }}
        {{- end }}
        {{- if .hostPath }}
        hostPath:
          path: /SharedFS{{ .hostPath.path }}
          type: {{ .hostPath.type }}
        {{- end }}
      {{- end }}
      {{- end }}
---
{{ if .Values.ports}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  {{ range .Values.ports }}
  {{ if .hostPort }}
  type: NodePort
  {{ end }}
  {{ end }}
  selector:
    app: {{ .Values.name }}-deployment
  ports:
  {{- range .Values.ports }}
  - name: {{ .port }}-{{ .protocol |  lower }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .port }}
    {{ if .hostPort }}
    nodePort: {{ .hostPort }}
    {{ end }}
  {{ end }}
{{ end }}
---
{{ if .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-job
  labels:
    app: {{ .Values.name }}-job
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .Values.name }}-job
        image: {{ .Values.jobs.image}}
        command: ["/bin/bash", "-c"]
        args:
        - |
        {{- range .Values.jobs.commands }}
            {{ .command }}
        {{- end }}

{{ end }}

