components:
- name: ubuntu
  image: ubuntu:latest
  active: true
  ports: 
  - port: 8080
    hostPort: 30001
  - port: 9090
  environment:
  - name: SOME_NUMBER_VAR
  	value: 89
  - name: ANOTHER_ENV_VAR
  	value: hola
  commands:
  - command: apt get update
  - command: apt install nginx
  volumes:
  - name: volume1
    directory: /path/to/a/folder/to/mount
    mountPath: /mount/path/of/folder
  - name: volume2
    file: /path/to/a/file/to/mount
    mountPath: /mount/path/of/file.config
  jobs:
    image: job-image:latest
    commands:
    - command: command that interact with another component
    - command: another bash command

- name: another-component
  image: another-component:latest
  ....... 
  ........