name: sp-worker

image: bde2020/spark-worker:3.3.0-hadoop3.3

replicas: 2

ports:
- port: 8081
  protocol: TCP

environment:
- name: SPARK_MASTER
  value: spark://sp-master:7077
- name: SPARK_WORKER_CORES
  value: "1"
- name: SPARK_WORKER_MEMORY
  value: "2g"
- name: SPARK_WORKER_WEBUI_PORT
  value: "8081"
- name: SPARK_EXECUTOR_MEMORY
  value: "2g"
- name: SPARK_WORKLOAD
  value: "worker"